name: Document Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs Repo
        uses: actions/checkout@v4

      - name: Setup typst
        uses: typst-community/setup-typst@v4

      - name: Build files
        run: |
          find . -type f -name "*.typ" ! -path "./templates/*" | parallel 'typst compile --format pdf --root . {} {.}.pdf'
          find . -name "*.pdf" -exec bash -c 'path="{}"; mkdir -p compiled/$(dirname "$path") && mv "$path" compiled/"$path"' \;

      - name: Deploy to Site Repo
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENSEGRETISSIMO }}
        run: |
          git clone "https://oauth2:$GITHUB_TOKEN@github.com/Sigma18Unipd/sigma18unipd.github.io.git" RepoSito
          cd RepoSito

          # Remove old files and copy new ones
          rm -rf ./documentiCompilati/[0-9]-*
          cp -r ../compiled/* ./documentiCompilati

          # Generate updated index.html
          cd ..
          python3 .github/workflows/generate_html.py

          # Commit changes
          cd RepoSito
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update documents: $(date +'%Y-%m-%d')"
          git push origin main
